### ISSUE TITLE
Add ability to add a PHP tag inside a string

### ISSUE THREAD

**Issue by ericseandevlin** [h4kst3r/php-awesome-snippets#2]
I often need to add a php tag _inside_ a string. This is common for WordPress development. I would like to be able to just type the letters php within a string and have it expand to the full tag with the cursor in the center surrounded with spaces - still within the string. For Example:

I would type php with the string of a div class like this:
`<div class="php"></div>`

Then it would expand to the full php tag like this ( the $1 being where the cursor would be placed after expansion )
`<div class="<?php $1 ?>"></div>`

**Comment by notiv-nt** [comment]
You can use "macros" (actually snippets) for that:
keybindings.json

```
{
  "key": "cmd+alt+p",
  "command": "editor.action.insertSnippet",
  "when": "editorTextFocus && !editorHasSelection",
  "args": {
    "snippet": "<?php $0 ?>"
  }
}
```


https://user-images.githubusercontent.com/10743009/106874369-8c763380-66e6-11eb-86d2-8ad40ba9da9a.mov
